'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class CmdResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Example.CmdResources", GetType(CmdResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access to {0} is not authorized by the operating system..
        '''</summary>
        Friend Shared ReadOnly Property AccessException() As String
            Get
                Return ResourceManager.GetString("AccessException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''UUEncode/UUDecode Utility
        '''.
        '''</summary>
        Friend Shared ReadOnly Property AppName() As String
            Get
                Return ResourceManager.GetString("AppName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UUEncode Error: /e and /d are mutually exclusive.
        '''.
        '''</summary>
        Friend Shared ReadOnly Property BadSwitches() As String
            Get
                Return ResourceManager.GetString("BadSwitches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UUEncode Error: File &apos;{0}&apos; not found.
        '''.
        '''</summary>
        Friend Shared ReadOnly Property FileNotFound() As String
            Get
                Return ResourceManager.GetString("FileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to    Syntax: UUEncode /? | [/e | /d] inFilename outFilename
        '''
        '''   Switches:
        '''         /?                  Displays this help.
        '''         /e                  Encode a file (the default)
        '''         /d                  Decode a file
        '''         /s:&lt;size&gt;      Encode/decode in &lt;size&gt; blocks.
        '''   Parameters:
        '''         inFileName    The file to be encoded/decoded.
        '''         outFilename   The encoded/decoded file to be created.
        '''.
        '''</summary>
        Friend Shared ReadOnly Property HelpText() As String
            Get
                Return ResourceManager.GetString("HelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An input/output exception occurred..
        '''</summary>
        Friend Shared ReadOnly Property IOException() As String
            Get
                Return ResourceManager.GetString("IOException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Decoded {0:N0} characters...                                       .
        '''</summary>
        Friend Shared ReadOnly Property ProgressDecodedMsg() As String
            Get
                Return ResourceManager.GetString("ProgressDecodedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Encoded {0:N0} bytes...               .
        '''</summary>
        Friend Shared ReadOnly Property ProgressEncodedMsg() As String
            Get
                Return ResourceManager.GetString("ProgressEncodedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You don&apos;t have permission to {0}..
        '''</summary>
        Friend Shared ReadOnly Property SecurityException() As String
            Get
                Return ResourceManager.GetString("SecurityException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully decoded {0} to {1}..
        '''</summary>
        Friend Shared ReadOnly Property SuccessDecodedMsg() As String
            Get
                Return ResourceManager.GetString("SuccessDecodedMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully encoded {0} to {1}..
        '''</summary>
        Friend Shared ReadOnly Property SuccessEncodedMsg() As String
            Get
                Return ResourceManager.GetString("SuccessEncodedMsg", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
