//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekRange {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeekRange.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Calculate.
        /// </summary>
        internal static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca&amp;lendar:.
        /// </summary>
        internal static string CalendarLabel {
            get {
                return ResourceManager.GetString("CalendarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eras:.
        /// </summary>
        internal static string EraLabel {
            get {
                return ResourceManager.GetString("EraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstDay.
        /// </summary>
        internal static string FirstDay {
            get {
                return ResourceManager.GetString("FirstDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;First Day of Week:.
        /// </summary>
        internal static string FirstDayOfWeekLabel {
            get {
                return ResourceManager.GetString("FirstDayOfWeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstFourDayWeek.
        /// </summary>
        internal static string FirstFourDayWeek {
            get {
                return ResourceManager.GetString("FirstFourDayWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstFullWeek.
        /// </summary>
        internal static string FirstFullWeek {
            get {
                return ResourceManager.GetString("FirstFullWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heisei|Showa|Taisho|Meiji.
        /// </summary>
        internal static string JapaneseEras {
            get {
                return ResourceManager.GetString("JapaneseEras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted date range to {0}/{1} to {2}/{3}.
        /// </summary>
        internal static string MSG_AdjustedRange {
            get {
                return ResourceManager.GetString("MSG_AdjustedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string MSG_Exception {
            get {
                return ResourceManager.GetString("MSG_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year field cannot be empty..
        /// </summary>
        internal static string MSG_YearEmpty {
            get {
                return ResourceManager.GetString("MSG_YearEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the year is invalid..
        /// </summary>
        internal static string MSG_YearFormat {
            get {
                return ResourceManager.GetString("MSG_YearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year is out of range..
        /// </summary>
        internal static string MSG_YearOutOfRange {
            get {
                return ResourceManager.GetString("MSG_YearOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Ranges:.
        /// </summary>
        internal static string ResultText {
            get {
                return ResourceManager.GetString("ResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rule.
        /// </summary>
        internal static string RuleLabel {
            get {
                return ResourceManager.GetString("RuleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Ranges:.
        /// </summary>
        internal static string WeekRangeLabel {
            get {
                return ResourceManager.GetString("WeekRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Week Ranges.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Year:.
        /// </summary>
        internal static string YearLabel {
            get {
                return ResourceManager.GetString("YearLabel", resourceCulture);
            }
        }
    }
}
